# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csv_redact1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSV_Redact(object):
    def setupUi(self, CSV_Redact):
        CSV_Redact.setObjectName("CSV_Redact")
        CSV_Redact.resize(800, 600)
        CSV_Redact.setStyleSheet("#centralwidget { \n"
"            background-image:url(\"pic1.jpg\"); background-position: center;}")
        self.centralwidget = QtWidgets.QWidget(CSV_Redact)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.first_text.setFont(font)
        self.first_text.setObjectName("first_text")
        self.verticalLayout.addWidget(self.first_text)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.choose_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.choose_btn.setFont(font)
        self.choose_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_btn.setStyleSheet("min-width:  176px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(124, 16, 255, 255), stop:1 rgba(205, 6, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"    max-width:  176px;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"    border-radius: 12px;\n"
"border: 4px groove rgb(170, 0, 255);")
        self.choose_btn.setObjectName("choose_btn")
        self.verticalLayout.addWidget(self.choose_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.current_file = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.current_file.setFont(font)
        self.current_file.setStyleSheet("border: 2px solid gray;\n"
"border-radius: 10px;")
        self.current_file.setObjectName("current_file")
        self.horizontalLayout.addWidget(self.current_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.transform_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.transform_btn.setFont(font)
        self.transform_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transform_btn.setStyleSheet("min-width:  196px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(124, 16, 255, 255), stop:1 rgba(205, 6, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"    max-width:  196px;\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"    border-radius: 24px;\n"
"border: 4px groove rgb(170, 0, 255);")
        self.transform_btn.setObjectName("transform_btn")
        self.verticalLayout_3.addWidget(self.transform_btn, 0, QtCore.Qt.AlignHCenter)
        self.ready_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.ready_label.setFont(font)
        self.ready_label.setText("")
        self.ready_label.setObjectName("ready_label")
        self.verticalLayout_3.addWidget(self.ready_label, 0, QtCore.Qt.AlignHCenter)
        self.amount_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.amount_label.setFont(font)
        self.amount_label.setText("")
        self.amount_label.setObjectName("amount_label")
        self.verticalLayout_3.addWidget(self.amount_label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        CSV_Redact.setCentralWidget(self.centralwidget)

        self.retranslateUi(CSV_Redact)
        QtCore.QMetaObject.connectSlotsByName(CSV_Redact)

    def retranslateUi(self, CSV_Redact):
        _translate = QtCore.QCoreApplication.translate
        CSV_Redact.setWindowTitle(_translate("CSV_Redact", "CSV файлы"))
        self.first_text.setText(_translate("CSV_Redact", "Вы выбрали режим работы с csv-файлами для следующего режима: "))
        self.choose_btn.setText(_translate("CSV_Redact", "Выбрать файл"))
        self.label_2.setText(_translate("CSV_Redact", "Текущий файл:"))
        self.transform_btn.setText(_translate("CSV_Redact", "Преобразовать"))
